
version: '3.7'
services:
  keptn-service:
    container_name: 'keptn-service-template-go'
    build: .
    depends_on:
      - 'distributor'
    ports:
      - '8080:8080'
    environment:
      - CONFIGURATION_SERVICE=http://configuration-service:8080
  distributor:
    image: 'keptn/distributor:0.12.1'
    container_name: 'keptn-distributor'
    ports:
      - '8080'
    environment:
      - PUBSUB_URL=nats://keptn-nats-cluster
      - PUBSUB_TOPIC=sh.keptn.>
      - PUBSUB_RECIPIENT=127.0.0.1
