apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keptn-service.fullname" . }}
  labels:
    {{- include "keptn-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "keptn-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keptn-service.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keptn-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: keptn-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
          - name: env
            value: 'production'
          - name: LOG_LEVEL
            value: 'debug'
          - name: PUBSUB_TOPIC
            value: {{ .Values.subscription.pubsubTopic }}
          - name: K8S_DEPLOYMENT_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
          - name: K8S_DEPLOYMENT_VERSION
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
          - name: K8S_DEPLOYMENT_COMPONENT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''app.kubernetes.io/component'']'
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          {{- if .Values.remoteControlPlane.enabled }}
          - name: KEPTN_API_ENDPOINT
            value: "{{ .Values.remoteControlPlane.api.protocol }}://{{ .Values.remoteControlPlane.api.hostname }}/api"
          - name: KEPTN_API_TOKEN
            value: "{{ .Values.remoteControlPlane.api.token }}"
          - name: HTTP_SSL_VERIFY
            value: "{{ .Values.remoteControlPlane.api.apiValidateTls | default "true" }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
